### ISSUE TITLE
AsyncDownloader.java line 177

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#21]
#### in uk.ac.ucl.excites.sapelli.collector.util.AsyncDownloader.onPostExecute

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/54ffd0907d7854d7c9b0cbfd](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/54ffd0907d7854d7c9b0cbfd)

**Comment by mstevens83** [comment]
Worked-around this in 910f176 by making the calling activity no longer restart upon screen orientation changes.
