### ISSUE TITLE
ProjectRunHelpers.java line 126

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#24]
#### in uk.ac.ucl.excites.sapelli.collector.util.ProjectRunHelpers.createShortcut

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5511a59c5141dcfd8f39392f](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5511a59c5141dcfd8f39392f)

**Comment by mstevens83** [comment]
Fixed in 3d0b3e2
