### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#25]
#### in com.symantec.starmobile.prowler.agent.TriggerHelper.getMethod
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5588004ef505b5ccf038281e](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5588004ef505b5ccf038281e)

**Comment by mstevens83** [comment]
This is mega weird. Besides the `CrashReporter` itself there is nothing in the stack traces that relates to Sapelli. Perhaps this is caused by a bug in Crashlytics itself.
Ignoring this...
