### ISSUE TITLE
ProjectRunHelpers.java line 126 [DUPLICATE]

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#26]
#### in uk.ac.ucl.excites.sapelli.collector.util.ProjectRunHelpers.createShortcut

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5511a59c5141dcfd8f39392f](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5511a59c5141dcfd8f39392f)

**Comment by mstevens83** [comment]
**BUILD_INFO**
*Built on 2015-06-19T11:28:54+01:00 by mstevens using master branch, revision 5411155 without changes*
**SAPELLI_DEVICE_ID_CRC32**
*1271669308*
**SAPELLI_LAST_RUNNING_PROJECT**
*ArcMap (v2.0) [id: 201506; fingerprint: 1829428676]*
**VERSION_INFO**
*Sapelli Collector v2.0.0-beta-15 [versionCode: 30369; release]*

**Device**
*XT1068* (= Motorola Moto G 2014) --> Louise/MfC??

**Comment by mstevens83** [comment]
Possibly useful info: http://stackoverflow.com/questions/7469082/getting-exception-illegalstateexception-can-not-perform-this-action-after-onsa

**Comment by mstevens83** [comment]
Fixed a while back, see #24.
