### ISSUE TITLE
Unable to access exported records via Android File Transfer on Mac

### ISSUE THREAD

**Issue by oliverroick** [ExCiteS/Sapelli#27]
I'm not able to download the exported CSV on my machine, apparently because files are not indexed when created by apps.

This could help: http://stackoverflow.com/questions/15007139/android-file-transfer-cannot-see-a-folder-created-by-app

**Comment by mstevens83** [comment]
I sometimes have this same problem on my windows machine. It's not a Mac problem, not a Windows problem, and not a Sapelli problem, it's an Android problem.
That said we may be able to work around it through a "Share" button like I did for the back-up feature.
