### ISSUE TITLE
ExportFragment.java line 198

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#39]
#### in uk.ac.ucl.excites.sapelli.collector.fragments.ExportFragment.setupUI

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/564a4189f5d3a7f76ba02ea9](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/564a4189f5d3a7f76ba02ea9)

**Comment by mstevens83** [comment]
4902f67 probably fixes this.
