### ISSUE TITLE
FileHelpers.java line 344

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#43]
#### in uk.ac.ucl.excites.sapelli.shared.io.FileHelpers.getSubDirectory

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/566e9a66f5d3a7f76b5798fb](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/566e9a66f5d3a7f76b5798fb)

**Comment by mstevens83** [comment]
Info:
```
BUILD_INFO
Built on 2015-09-24T23:34:24-03:00 by mstevens using master branch, revision 5a78ae5 without changes
VERSION_INFO
Sapelli Collector v2.0.0-beta-16 [versionCode: 32709; release]
 SAPELLI_DEVICE_ID_CRC32
1777574234
SAPELLI_DEVICE_ID_MD5
-96540628015853607456021934361013385459
```

**Comment by mstevens83** [comment]
Root cause is this:
```
Could not create directory: /storage/sdcard/Android/data/uk.ac.ucl.excites.sapelli.collector/files/Temp
```
No idea how this can happen, `CollectorApp#initialiseFileStorage()` should have ensured we have a writeable working folder.
Maybe the SD card was taken out while Sapelli was running? (Is that even possible?)

**Comment by mstevens83** [comment]
This and similar crashes should no longer be possible thanks to 23324282f443689d5b3b348fee8c3ceb2ecdf384.
