### ISSUE TITLE
ProjectManagerFragment.java line 97

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#47]
#### in uk.ac.ucl.excites.sapelli.collector.fragments.ProjectManagerFragment.addChild

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/56920ae5f5d3a7f76bf9d2c2](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/56920ae5f5d3a7f76bf9d2c2)

**Comment by mstevens83** [comment]
Duplicate of #38.
