### ISSUE TITLE
Update wiki with screenshots of new project management UI

### ISSUE THREAD

**Issue by mstevens83** [ExCiteS/Sapelli#49]
http://wiki.sapelli.org/index.php/Introduction_to_the_Sapelli_Collector_app

**Comment by EmpressNaledi** [comment]
@juliusosokinas is creating some UI screen shots

**Comment by EmpressNaledi** [comment]
![screenshot_2016-02-03-15-09-01](https://cloud.githubusercontent.com/assets/12254027/12819453/1f377b28-cb53-11e5-8038-934bf220f9c5.png)
![screenshot_2016-02-03-15-12-26](https://cloud.githubusercontent.com/assets/12254027/12819454/1f392716-cb53-11e5-8305-4f4f1f6f602e.png)
![screenshot_2016-02-03-15-18-49](https://cloud.githubusercontent.com/assets/12254027/12819455/1f3f7a12-cb53-11e5-9d13-b94105ffd269.png)
![screenshot_2016-02-03-15-23-45](https://cloud.githubusercontent.com/assets/12254027/12819456/1f413c6c-cb53-11e5-9030-105cafe6bd7f.png)
![screenshot_2016-02-03-15-42-43](https://cloud.githubusercontent.com/assets/12254027/12819457/1f42a228-cb53-11e5-8dff-268301cd99e0.png)
![screenshot_2016-02-03-15-42-46](https://cloud.githubusercontent.com/assets/12254027/12819458/1f44e218-cb53-11e5-9789-5f0c335a2ccd.png)
![screenshot_2016-02-03-15-43-02](https://cloud.githubusercontent.com/assets/12254027/12819460/1f5fb1a6-cb53-11e5-8ca5-3ce119fc2fc2.png)
![screenshot_2016-02-03-15-43-27](https://cloud.githubusercontent.com/assets/12254027/12819459/1f58baa4-cb53-11e5-9860-fc70c4360f9d.png)

**Comment by mstevens83** [comment]
Good, that's a start. Now someone should update the wiki page(s) using those screenshots.
Maybe if I'm bored, but fixing the last bugs I know of is higher priority ;-).
