### ISSUE TITLE
CollectorView.java line 530

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#68]
#### in uk.ac.ucl.excites.sapelli.collector.ui.CollectorView.getFieldUIPartHeightPx

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/573c5dcdffcdc04250065e55](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/573c5dcdffcdc04250065e55)

**Comment by mstevens83** [comment]
Fixed in 9dea165.
