### ISSUE TITLE
CollectorController.java line 957

### ISSUE THREAD

**Issue by Sapelli** [ExCiteS/Sapelli#72]
#### in uk.ac.ucl.excites.sapelli.collector.control.CollectorController.getCurrentForm

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5762f378ffcdc0425065924f](https://fabric.io/ucl-excites/android/apps/uk.ac.ucl.excites.sapelli.collector/issues/5762f378ffcdc0425065924f)

**Comment by mstevens83** [comment]
Fixed in d5021d7.
